catalog/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView
from .api_views import ProductListAPIView

urlpatterns = [
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="product_detail"),
    path("api/products/", ProductListAPIView.as_view(), name="api_product_list"),
    path("", ProductListView.as_view(), name="product_list"),
]

product_catalog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.utils.text import slugify


class ProductAttribute(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(ProductAttribute, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    stylized_description = models.TextField()
    image = models.ImageField(upload_to="products/")
    attributes = models.ManyToManyField(
        ProductAttribute, through="ProductAttributeValue"
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse("product_detail", kwargs={"slug": self.slug})


class ProductAttributeValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    attribute = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE)
    value = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.product.name} - {self.attribute.name}: {self.value}"

catalog/views.py
from django.views.generic import ListView, DetailView
from .models import Product


class ProductListView(ListView):
    model = Product
    template_name = "product_list.html"


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_detail.html"

catalog/templates/product_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ product.name }}</title>
</head>
<body>
    <h1>{{ product.name }}</h1>
    <img src="{{ product.image.url }}" alt="{{ product.name }}" width="300" height="300">
    <p>{{ product.description }}</p>
    <p>{{ product.stylized_description|safe }}</p>
    
    <h2>Attributes</h2>
    <ul>
    {% for attr_value in product.productattributevalue_set.all %}
        <li><strong>{{ attr_value.attribute.name }}:</strong> {{ attr_value.value }}</li>
    {% endfor %}
    </ul>
</body>
</html>

catalog/templates/product_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Product Catalog</title>
</head>
<body>
<h1>Product Catalog</h1>
<ul>
    {% for product in object_list %}
    <li>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <p>{{ product.stylized_description|safe }}</p>
        <br>
        <img src="{{ product.image.url }}" alt="{{ product.name }}" width="100" height="100">>
    </li>
    {% endfor %}
</ul>
</body>
</html>